# Generated by Django 4.2.5 on 2023-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_production_system', '0011_mentor_team_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
